// <auto-generated />
using System;
using HomemadeGit.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HomemadeGit.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260627063954_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("HomemadeGit.Core.Models.Blob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Size")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Hash")
                        .IsUnique();

                    b.ToTable("Blobs");
                });

            modelBuilder.Entity("HomemadeGit.Core.Models.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HeadCommitId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RepositoryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HeadCommitId");

                    b.HasIndex("RepositoryId", "Name")
                        .IsUnique();

                    b.ToTable("Branches");
                });

            modelBuilder.Entity("HomemadeGit.Core.Models.Commit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentCommitId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RepositoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ParentCommitId");

                    b.HasIndex("UserId");

                    b.HasIndex("RepositoryId", "Hash")
                        .IsUnique();

                    b.ToTable("Commits");
                });

            modelBuilder.Entity("HomemadeGit.Core.Models.CommitFiles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BlobId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CommitId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BlobId");

                    b.HasIndex("CommitId", "Path")
                        .IsUnique();

                    b.ToTable("CommitFiles");
                });

            modelBuilder.Entity("HomemadeGit.Core.Models.Repository", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DefaultBranchId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DefaultBranchId");

                    b.HasIndex("OwnerId", "Name")
                        .IsUnique();

                    b.ToTable("Repositories");
                });

            modelBuilder.Entity("HomemadeGit.Core.Models.Roles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("HomemadeGit.Core.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HomemadeGit.Core.Models.UserRepository", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("RepositoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserRoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId");

                    b.HasIndex("UserRoleId");

                    b.HasIndex("UserId", "RepositoryId")
                        .IsUnique();

                    b.ToTable("UserRepositories");
                });

            modelBuilder.Entity("HomemadeGit.Core.Models.Branch", b =>
                {
                    b.HasOne("HomemadeGit.Core.Models.Commit", "HeadCommit")
                        .WithMany()
                        .HasForeignKey("HeadCommitId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HomemadeGit.Core.Models.Repository", "Repository")
                        .WithMany("Branches")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HeadCommit");

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("HomemadeGit.Core.Models.Commit", b =>
                {
                    b.HasOne("HomemadeGit.Core.Models.Commit", "ParentCommit")
                        .WithMany()
                        .HasForeignKey("ParentCommitId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HomemadeGit.Core.Models.Repository", "Repository")
                        .WithMany("Commits")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HomemadeGit.Core.Models.User", "User")
                        .WithMany("Commits")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentCommit");

                    b.Navigation("Repository");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HomemadeGit.Core.Models.CommitFiles", b =>
                {
                    b.HasOne("HomemadeGit.Core.Models.Blob", "Blob")
                        .WithMany("CommitFiles")
                        .HasForeignKey("BlobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HomemadeGit.Core.Models.Commit", "Commit")
                        .WithMany("CommitFiles")
                        .HasForeignKey("CommitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Blob");

                    b.Navigation("Commit");
                });

            modelBuilder.Entity("HomemadeGit.Core.Models.Repository", b =>
                {
                    b.HasOne("HomemadeGit.Core.Models.Branch", "DefaultBranch")
                        .WithMany()
                        .HasForeignKey("DefaultBranchId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HomemadeGit.Core.Models.User", "Owner")
                        .WithMany("OwnedRepositories")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DefaultBranch");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("HomemadeGit.Core.Models.UserRepository", b =>
                {
                    b.HasOne("HomemadeGit.Core.Models.Repository", "Repository")
                        .WithMany("UserRepositories")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HomemadeGit.Core.Models.User", "User")
                        .WithMany("UserRepositories")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HomemadeGit.Core.Models.Roles", "UserRole")
                        .WithMany("UserRepositories")
                        .HasForeignKey("UserRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repository");

                    b.Navigation("User");

                    b.Navigation("UserRole");
                });

            modelBuilder.Entity("HomemadeGit.Core.Models.Blob", b =>
                {
                    b.Navigation("CommitFiles");
                });

            modelBuilder.Entity("HomemadeGit.Core.Models.Commit", b =>
                {
                    b.Navigation("CommitFiles");
                });

            modelBuilder.Entity("HomemadeGit.Core.Models.Repository", b =>
                {
                    b.Navigation("Branches");

                    b.Navigation("Commits");

                    b.Navigation("UserRepositories");
                });

            modelBuilder.Entity("HomemadeGit.Core.Models.Roles", b =>
                {
                    b.Navigation("UserRepositories");
                });

            modelBuilder.Entity("HomemadeGit.Core.Models.User", b =>
                {
                    b.Navigation("Commits");

                    b.Navigation("OwnedRepositories");

                    b.Navigation("UserRepositories");
                });
#pragma warning restore 612, 618
        }
    }
}
